### ISSUE TITLE
Drop support for Python 3.2

### ISSUE THREAD

**Issue by grodtron** [pfpsim/pfpdb#5]
It seems that the python protobuf library does not support v3.2. This is causing build [26.2](https://travis-ci.org/pfpsim/pfpdb/jobs/135682681) to fail with:

```
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (type_checkers.py, line 180))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/pfpsim/pfpdb/tests.py", line 1, in <module>
    from pfpdb.pfpdb import DebuggerIPCSession
  File "/home/travis/build/pfpsim/pfpdb/pfpdb/pfpdb.py", line 52, in <module>
    from . import PFPSimDebugger_pb2
  File "/home/travis/build/pfpsim/pfpdb/pfpdb/PFPSimDebugger_pb2.py", line 9, in <module>
    from google.protobuf import reflection as _reflection
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/google/protobuf/internal/python_message.py", line 67, in <module>
    from google.protobuf.internal import type_checkers
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/google/protobuf/internal/type_checkers.py", line 180
    return u""
             ^
SyntaxError: invalid syntax
```

You can also see in [the protobuf test script](https://github.com/google/protobuf/blob/master/tests.sh#L232) that they only test on 2.6, 2.7, 3.3, 3.4.

Based on this I vote we don't try to support 3.2.

@uaftab what do you think?

**Comment by uaftab** [comment]
Yeah I think we should drop it pfpdb py3.2 :-1:
